/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef contact_info_CONSTANTS_H
#define contact_info_CONSTANTS_H

#include "contact_info_types.h"

namespace kad {

class contact_infoConstants {
 public:
  contact_infoConstants();

};

extern const contact_infoConstants g_contact_info_constants;

} // namespace

#endif
