/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "contact_info_constants.h"

namespace kad {

const contact_infoConstants g_contact_info_constants;

contact_infoConstants::contact_infoConstants() {
}

} // namespace

