/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "kademlia_service_constants.h"

namespace kad {

const kademlia_serviceConstants g_kademlia_service_constants;

kademlia_serviceConstants::kademlia_serviceConstants() {
}

} // namespace

