/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "kademlia_service_messages_constants.h"

namespace kad {

const kademlia_service_messagesConstants g_kademlia_service_messages_constants;

kademlia_service_messagesConstants::kademlia_service_messagesConstants() {
}

} // namespace

