/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef kademlia_service_messages_CONSTANTS_H
#define kademlia_service_messages_CONSTANTS_H

#include "kademlia_service_messages_types.h"

namespace kad {

class kademlia_service_messagesConstants {
 public:
  kademlia_service_messagesConstants();

};

extern const kademlia_service_messagesConstants g_kademlia_service_messages_constants;

} // namespace

#endif
