/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef kademlia_service_CONSTANTS_H
#define kademlia_service_CONSTANTS_H

#include "kademlia_service_types.h"

namespace kad {

class kademlia_serviceConstants {
 public:
  kademlia_serviceConstants();

};

extern const kademlia_serviceConstants g_kademlia_service_constants;

} // namespace

#endif
