/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef signed_kadvalue_CONSTANTS_H
#define signed_kadvalue_CONSTANTS_H

#include "signed_kadvalue_types.h"

namespace kad {

class signed_kadvalueConstants {
 public:
  signed_kadvalueConstants();

};

extern const signed_kadvalueConstants g_signed_kadvalue_constants;

} // namespace

#endif
