/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "signed_kadvalue_constants.h"

namespace kad {

const signed_kadvalueConstants g_signed_kadvalue_constants;

signed_kadvalueConstants::signed_kadvalueConstants() {
}

} // namespace

